### ISSUE TITLE
How do I wait for complete initialization Tor

### ISSUE THREAD

**Issue by b1tc0re** [joelverhagen/TorSharp#10]
Help me understand please. How do I wait for complete initialization Tor + Privoxy. To use a proxy server 127.0.0.1:8118

**Comment by joelverhagen** [comment]
Currently, the best way to detect this is by sending a test HTTP request to the HTTP proxy. It looks like `tor.exe` emits some log messages to stdout that I could detect before completing `ConfigureAndStartAsync`. However, you still need to wait for Privoxy to get started...

I'll keep this bug open while I think about an convenient way for devs to detect when initialization is done. In the mean time, consider Tor and Privoxy ready after a test HTTP request make it through (e.g. to Google).

**Comment by nopara73** [comment]
Actually asking the ControlPort for `GETINFO status/circuit-established` or `GETINFO dormant` is the the proper way: https://stackoverflow.com/questions/37135213/check-tor-connection-is-established-before-running-scrapy  
  
It's pretty straightforward, though you can take a look at my implementation of 
 `GETINFO status/circuit-established` if stuck: https://github.com/nopara73/DotNetTor/blob/master/src/DotNetTor/ControlPort/Client.cs

**Comment by joelverhagen** [comment]
Yeah, thanks for the additional information @nopara73. That's a great point.

For the purposes of this project, I'm going to limit this to just sending an HTTP request. The first HTTP request might take a little longer since it is waiting for Tor and Privoxy to finish their initialization.

**Comment by joelverhagen** [comment]
I've added `TorSharpSettings.WaitForConnect` to help with this. It defaults to waiting for up to 5 seconds during initialization.
