### ISSUE TITLE
Docker Alpine An error occurred trying to start process '/tmp/TorExtracted/tor-linux64-12.0.6/tor/tor'  No such file or directory

### ISSUE THREAD

**Issue by theRealBaccata** [joelverhagen/TorSharp#103]
Hello,

I'm facing some issue after switching my current Docker**base**image from Debian (11) to Alpine (3.17)

While everything works like a charm in Debian

> mcr.microsoft.com/dotnet/aspnet:6.0

I fail to get pass this line of code

> await proxy.ConfigureAndStartAsync();

using Alpine

> mcr.microsoft.com/dotnet/aspnet:6.0-alpine

Error message:
```An error occurred trying to start process '/tmp/TorExtracted/tor-linux64-12.0.6/tor/tor' with working directory '/tmp/TorExtracted/tor-linux64-12.0.6/tor'. No such file or directory```

Stack trace:
```   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Knapcode.TorSharp.Tools.SimpleToolRunner.StartAsync(Tool tool) in /_/src/TorSharp/Tools/SimpleToolRunner.cs:line 32
   at Knapcode.TorSharp.TorSharpProxy.StartAsync(Tool tool) in /_/src/TorSharp/TorSharpProxy.cs:line 230
   at Knapcode.TorSharp.TorSharpProxy.StartAsync() in /_/src/TorSharp/TorSharpProxy.cs:line 150
   at Knapcode.TorSharp.TorSharpProxy.ConfigureAndStartAsync() in /_/src/TorSharp/TorSharpProxy.cs:line 102
```

It's worth adding that the files actually exist inside the (alpine) docker container:

![Alpine](https://github.com/joelverhagen/TorSharp/assets/12572377/c89c8e5a-dab3-4671-9867-50ce0bfae9fb)

Versions:
```
Knapcode.TorSharp: 2.14.0
ASP.NET: 6.0.11
.NET: 6.0.11
Docker Engine: 23.0.5
```

**Comment by joelverhagen** [comment]
I haven't tested on Alpine at all. This seems like something I should be able to do easily with WSL.

Thanks for the detailed report. I'll leave this open until I have time to investigate Alpine.

**Comment by joelverhagen** [comment]
The file path appears correct and the `tor` binary is marked as executable. Maybe try running `chmod +x` manually on it and invoking `tor` on your own to see if it runs without TorSharp? This may help narrow the problem.

**Comment by joelverhagen** [comment]
Okay, I think I know what's going on. I was able to repro the problem by modifying the https://github.com/joelverhagen/TorSharp/blob/release/samples/Docker/Dockerfile sample. The official Tor distribution is meant for glibc and Alpine is based on libmusl. Thankfully I have learned about this difference at my job. You will need to use the ported version of Tor on Alpine that runs on libmusl. Someone has done this work already and `tor` is available in the default distribution of Alpine so you can just run `apk add tor privoxy`. Or you can disable privoxy and use native Socks support (see samples and README). Either way, you need a compatible version or `tor` which the built-in fetcher cannot provide due to a missing official distribution.

I got it working with this Dockerfile
https://github.com/joelverhagen/TorSharp/blob/release/samples/Docker-Alpine/Dockerfile

**Comment by theRealBaccata** [comment]
Hello @joelverhagen,

Thank you very much for taking a closer look.

Thanks to your provided example, I was also able to get it running using `Alpine`.

**Some notes for other devs:**

For me, it wasn't necessary to either run `RUN cat /etc/os-release` nor install `privoxy`. Also reduced the `TorSharpSettings` to one line, which is mandatory for my code to run: `ExecutablePathOverride = "tor"` all other lines are negligible.

Unfortunately this very line broke my `Debian` docker image and all non-Docker builds. So I just added a new environment variable to my `Alpine` dockerfile:

```
ENV IS_ALPINE_DOCKER_IMAGE=true
```

and wrote a small helper method to only set `ExecutablePathOverride` if needed:

```
    private static TorSharpSettings CreateTorSharpSettings()
    {
        TorSharpSettings settings = new TorSharpSettings
        {
            [...]
            ToolRunnerType = ToolRunnerType.Simple, // https://github.com/joelverhagen/TorSharp/issues/100
            PrivoxySettings =
            {
                Disable = true
            }
        };

        if (IsAlpineDockerImage())
            settings.TorSettings = new TorSharpTorSettings { ExecutablePathOverride = "tor" };

        return settings;
    }

    private static bool IsAlpineDockerImage()
    {
        ReadOnlySpan<char> environmentVariable = Environment.GetEnvironmentVariable("IS_ALPINE_DOCKER_IMAGE", EnvironmentVariableTarget.Process);
        _ = bool.TryParse(environmentVariable, out bool isAlpineDockerImage);

        return isAlpineDockerImage;
    }
```
