### ISSUE TITLE
Virtual desktop not working on windows 11

### ISSUE THREAD

**Issue by tix** [joelverhagen/TorSharp#105]
I am trying the default configuration of starting initializing tor in windows 11 and I get a black command window running tor.exe. The exact same code works perfectly on windows 10. Do you know if I need to change something on the virtual desktop configuration ?

**Comment by joelverhagen** [comment]
I have Windows 11 and it's working just fine. But I have heard from other users that the virtual desktop mode is flaky is different ways over the years. If you're facing trouble, I recommend just using the simple tool runner by setting `ToolRunnerType = ToolRunnerType.Simple` on the `TorSharpSettings`. If you figure out the problem, please feel free to open a PR with a fix and I'll take a look! Or, if you have a minimal repro on, say, a cloud-hosted VM of Windows 11 that I can use to investigate the issue, that could help too.
