### ISSUE TITLE
No version of Tor could be found under base URL (It is happening again)

### ISSUE THREAD

**Issue by i-lamrani** [joelverhagen/TorSharp#108]
TorSharpException: No version of Tor could be found under base URL https://dist.torproject.org/torbrowser/ with pattern tor-win64-(?[\d.]+).zip$.

this is issue happened last year, they changed the position of the version it would be very helpful if we could override the pattern that detected the available versions.

**Comment by i-lamrani** [comment]
https://github.com/joelverhagen/TorSharp/pull/109

**Comment by joelverhagen** [comment]
Fixed with 2.15.0: https://www.nuget.org/packages/Knapcode.TorSharp/2.15.0

Thanks for your PR contribution @i-lamrani!
