### ISSUE TITLE
Knapcode.TorSharp.TorSharpException: 'No version of Tor could be found under base URL

### ISSUE THREAD

**Issue by dprequim** [joelverhagen/TorSharp#112]
I am a newbie in using TorSharp and run into a error here, I do not know what to do to change the base URL. 

![image](https://github.com/joelverhagen/TorSharp/assets/35822384/9d334969-be60-4301-9931-44170cd3d420)

**Comment by joelverhagen** [comment]
This is due to Tor changing the file name pattern on their official distribution. This is fixed in the release branch and I'm working on releasing a 2.15.0 package version.

**Comment by joelverhagen** [comment]
Fixed with 2.15.0: https://www.nuget.org/packages/Knapcode.TorSharp/2.15.0
