### ISSUE TITLE
Tor Download/Extraction Issues

### ISSUE THREAD

**Issue by whiterabb17** [joelverhagen/TorSharp#114]
Hey, i noticed the tor download stopping working the otherday - the fix which you applied already, just changing the version to the end of the search pattern.
Which made the library work again properly for a day or 2.
Now its having issues completely downloading the tor files so it just cancels the download.
If i provide the downloaded files for tor using the pattern its looking for - it then has issues trying to extract the archive.

Do you have any idea what could be causing this?

**Comment by joelverhagen** [comment]
I don't know what would be causing this. I think to debug it you should take a look at a Fiddler trace (on Windows) or perhaps a mitmproxy trace (on Linux) of the tool fetching routine. If all else fails, consider setting up the tools manually:
https://github.com/joelverhagen/TorSharp#how-do-i-set-up-the-tools-manually

**Comment by whiterabb17** [comment]
I'll take a look, it seems to be affecting a few people trying use the library that i know. So at this point its not an isolated case but ill give it a look under fiddler

**Comment by olaftnt** [comment]
Hi, i encountered a similar issue and resolved it by obtaining the latest package version 2.15.0

**Comment by whiterabb17** [comment]
Thanks alot ill check it out
