### ISSUE TITLE
Cross platform support? .NET Core? .NET Standard?

### ISSUE THREAD

**Issue by joelverhagen** [joelverhagen/TorSharp#12]
The feasibility of this should be investigate. Both Privoxy and Tor are cross-platform tools. The Virtual Desktop trick certainly won't work though :)

**Comment by IvanKonov** [comment]
need net 4.0 and below

**Comment by nopara73** [comment]
I am putting together some tor stuff in dotnet core, partially based on your previous https://github.com/joelverhagen/SocketToMe project, if I am right this TorSharp is based on that, too.  It is different and minimal, but might be worth mentioning: https://github.com/nopara73/DotNetTor  
I would not started it if your library would be cross-platform (or anybody else's), though.

**Comment by joelverhagen** [comment]
SocketToMe is not used in TorSharp. SocketToMe is really just a toy project without much polish. Privoxy is used here instead to essentially map a SOCKS endpoint to an HTTP proxy endpoint (which is natively supported by .NET Framework).

**Comment by wesamco** [comment]
now that [.NET Core 2.0 Preview 1](https://blogs.msdn.microsoft.com/dotnet/2017/05/10/announcing-net-core-2-0-preview-1/) is out, with Massive API increase (>100%) relative to .NET Core 1.x. , can we have an update? 
I'm happy to contribute. 😃

**Comment by nopara73** [comment]
I'm confused as always with .NET Core's naming ecosystem. @wesamco Do you know why isn't .NET Core 2 is the default what Microsoft is recommending to its users? https://www.microsoft.com/net/core  
Is this unstable and only an RC/alpha/beta or something, what the preview wants to denote?

**Comment by wesamco** [comment]
.NET Core 1.0 was released one year ago, with a preview release 3-4 months before the final release. 1.1.x was released after. one year later, .NET Core 2.0 is getting ready, and has been released as Preview 1, and the final release will be in Q3 2017.
.NET Core 2 runs .NET Standard 2.0, and .NET Standard 2.0 at least in my mind is the full Windows .NET Framework excluding Windows only APIs like WPF and Win Forms etc..
so [these](https://github.com/joelverhagen/TorSharp/blob/master/src/Knapcode.TorSharp/TorSharpProxy.cs#L1-L8) packages are most likely in the .NET Standard 2.0.

**Comment by joelverhagen** [comment]
One of the challenges of this issue is developing a strategy to pick the right Tor and Privoxy binaries per platform. I am thinking for Linux and Mac OS X to assume Tor and Privoxy are already in the `PATH`. Thoughts?

**Comment by nopara73** [comment]
> Assume Tor is already in the path  
  
I did this before. So I can provide a couple of notes.   
  
- A side note: If you don't assume Tor is in the path and would rather ship it with software you would end up in messy permission issues in some operating systems when you would want to programatically launch it. Of course cleaning up the mess is a possibility, but it's really time consuming do it properly.  
- A small note: if you assume Tor is in the path, when you put Tor to path, after that you need to restart Visual Studio (vs2017), otherwise it won't pick it up.  
- If Tor is already running, Tor will be closed if the application shares any of these configuration: ControlPort, SOCKSPort, DataDirectory.   
- When you first launch Tor with a new datadirectory about 1/4 time it doesn't estabilish the circuit `status/circuit-established=1`. It's strange, I don't experience it from cmd, but from .NET Core code (win7). Anyway I hacked around this issue by restarting Tor when this happens. When it messed something into the datadirectory, starting next time it won't have this issue.

**Comment by nopara73** [comment]
@joelverhagen I completely rewrote the HTTP parser from scratch based on the rfc in my Tor library. And heavily commented it. The legacy parser I was using was simply taken from your sockettome project. I think it's pretty decent work so just as a tip if you feel like removing the privoxy dependency you have everything you need.  
  
It works with HTTP/1.0 and 1.1, and in fact if you feel like and have time in the future we could even give out a shared http proxy nuget, could even support http2.

**Comment by AbeniMatteo** [comment]
@joelverhagen Are you working on this?
Have you solved the problem with `System.ServiceModel`?

**Comment by joelverhagen** [comment]
Yeah originally I was going to replace it with manual XML parsing but turns out the .NET team released a cross-platform implementation of service model.

Actually have a branch working on Ubuntu. The CI randomly hangs though so I'm not sure about the quality yet. Would you be interested in a pre-release build pushed up to nuget.org? No Mac OS support yet.

**Comment by AbeniMatteo** [comment]
I'm interested on the new target `nestandard`, currently i'm using an adaptation of your old work that manually parses the various feeds and have no dependency on `System.ServiceModel`.
For now it runs fine targeted for netstandard2.0-netcoreapp3.0.

No need to publish on Nuget, i'm already set up to compile and test. Tomorrow i'll test the changes.

**Comment by joelverhagen** [comment]
What operating system are you running on? Where are you getting For? Is it installed to your machine? The branch I'm working on right now downloads Tor on the fly from the Tor distribution website.

**Comment by AbeniMatteo** [comment]
I have a netcoreapp3.0 running on windows where i will test your changes related to the targeting. I cannot help you with the Linux part.

There no problem to be solved, i forked this repo (few months ago), applied your old changes (from a branch that now probably is deleted) and imported the compiled dll from a local nuget folder.
I was just informing you that i'm glad that you're working on this and i'm already setup to test the changes without wasting your time publishing a prerelease package.

I'm sorry for the confusion.

**Comment by joelverhagen** [comment]
Hey everyone, I shipped version [2.0.0-beta1](https://www.nuget.org/packages/Knapcode.TorSharp/2.0.0-beta1) that has support for netstandard2.0. It currently only works on Windows. Exceptions are thrown at runtime if the code is running on a platform that is not Windows. This is because acquiring Tor and Privoxy today is hard coded to get the Win32 binaries.

I have Linux support working well on Ubuntu 18.04 locally and 16.04 working on a Travis CI, but it's not quite ready yet.

I hope to release a stable 2.0.0 version with Linux support.

If you run into any issues with .NET Core support on Windows, feel free to open another issue. For now, I am closing this one since .NET Core support is done.

**Comment by joelverhagen** [comment]
Linux support is available in [2.0.0](https://www.nuget.org/packages/Knapcode.TorSharp/2.0.0).
