### ISSUE TITLE
Nuget Update

### ISSUE THREAD

**Issue by Spegeli** [joelverhagen/TorSharp#15]
Will you Update the Nuget Repo (https://www.nuget.org/packages/Knapcode.TorSharp) to the last changes:
https://github.com/joelverhagen/TorSharp/commit/1273e8e994ae8c314c9fd28619517befd1ff3921 ?

**Comment by joelverhagen** [comment]
This commit is almost completely untested. I haven't had a chance to make sure I didn't regress Windows functionality.

**Comment by joelverhagen** [comment]
Also, Linux/Mac OS support is not ready.

**Comment by joelverhagen** [comment]
This issue is tracked by https://github.com/joelverhagen/TorSharp/issues/12.
