### ISSUE TITLE
Failed to download Tor?

### ISSUE THREAD

**Issue by kerryjiang** [joelverhagen/TorSharp#16]
Our system started receiving this error. It seems the application cannot download the Tor successfully.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Knapcode.TorSharp.TorSharpToolFetcher.<DownloadFileAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Knapcode.TorSharp.TorSharpToolFetcher.<FetchAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by kerryjiang** [comment]
I tried to debug the source code but I found the solution file and project files were upgraded to .NET core.

**Comment by kerryjiang** [comment]
Oh, Tor didn't release any win32 files in 7.0.3:
https://dist.torproject.org/torbrowser/7.0.3/

**Comment by JLaw0351** [comment]
my tor version is 7.0.2

**Comment by kerryjiang** [comment]
The application always tries to download the latest one.

So you can walk around this issue by skipping the downloading step.

**Comment by JLaw0351** [comment]
//ZippedToolsDirectory = ...
 //ExtractedToolsDirectory = ...

tried commenting them both out. same issue

**Comment by kerryjiang** [comment]
Just comment this line if the previous version Tor was downloaded already:

//await new TorSharpToolFetcher(settings, new HttpClient()).FetchAsync();

**Comment by joelverhagen** [comment]
I'm taking a look now. @kerryjiang, looks like you're right. 7.0.3 does not have a Windows build.

**Comment by JLaw0351** [comment]
@kerryjiang , let me know what you come up with! thanks @joelverhagen , I will try as well... that is probably why the tor was not downloading in the download routine!

**Comment by joelverhagen** [comment]
I've pushed a new NuGet package (version 1.6.1) with the fix. Let me know if you have any other issues by re-opening this issue!
https://preview.nuget.org/packages/Knapcode.TorSharp/1.6.1

Note that I just pushed the package so you should be able to see it within 10 minutes in Visual Studio.

**Comment by JLaw0351** [comment]
@joelverhagen , you are a seriously cool dude man. THANKS A TON! that did it. So basically if I can get this running ANYONE can get it as a C# guy... truly cool thanks!

**Comment by joelverhagen** [comment]
Haha, glad to hear it! If you have feature requests or run into any other issues, I'd love to hear about it. Feel free to open an issue for anything you think of. I may not get to it quickly, but I am certainly interested.

**Comment by kerryjiang** [comment]
@joelverhagen  so no new CefSharp package in nuget for now? Only for Knapcode.TorSharp?

**Comment by joelverhagen** [comment]
@kerryjiang, not sure what you mean. Which CefSharp package you referring to?

**Comment by kerryjiang** [comment]
@joelverhagen Sorry, I messed up with something else. Your fix works, thank you so much!
