### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by EDelfosse** [joelverhagen/TorSharp#18]
Is there a list of functions and classes for TorSharp and their uses?
Thanks

**Comment by joelverhagen** [comment]
Nope, the best that exists today is the source 😨. Do you have any specific questions? A good place to start is looking at the sample project:
https://github.com/joelverhagen/TorSharp/blob/6059777b89af3bd5eaa30ae790eeac636e84201f/samples/Knapcode.TorSharp.Sandbox/Program.cs
