### ISSUE TITLE
Dependency required for this

### ISSUE THREAD

**Issue by anandtpatel** [joelverhagen/TorSharp#19]
Can you please update readme file to add what dependency required to use this library or it will auto download them ? @joelverhagen

**Comment by joelverhagen** [comment]
The Knapcode.TorSharp 1.6.1 package has not additional dependencies other than the .NET Framework. It runs on .NET Framework 4.5.

In general, if you install a NuGet package, all dependencies should be pulled in for you.

**Comment by anandtpatel** [comment]
I have latest version installed.

![image](https://user-images.githubusercontent.com/7657501/31298431-1dcda2da-aab8-11e7-9918-ee6d594bfb69.png)

I am getting issue with few stuff not getting resolved, for 4.5 framework.

![image](https://user-images.githubusercontent.com/7657501/31298496-60a31c52-aab8-11e7-95d8-d1ad383573cd.png)

**Comment by joelverhagen** [comment]
If you are looking at the Sandbox code on `master` branch, there is no package supporting that yet.
https://github.com/joelverhagen/TorSharp/blob/master/samples/Knapcode.TorSharp.Sandbox/Program.cs

I would recommend looking at the Sandbox on the `release` branch:
https://github.com/joelverhagen/TorSharp/blob/release/TorSharp.Sandbox/Program.cs
