### ISSUE TITLE
VirtualDesktop broken since Win10 Creators Update?

### ISSUE THREAD

**Issue by Spegeli** [joelverhagen/TorSharp#20]
Since the Creators Update of Windows 10, it seems that ToolRunnerType.VirtualDesktop seems broken because of API changes. 
Here is a Screenshot which says the Error Code and that tor.exe cant be started correct: http://i.epvpimg.com/ro79eab.png

ToolRunnerType.Simple is still working correct.

Would be nice if can take a look at this issue.

**Comment by joelverhagen** [comment]
Odd, I gave this a try on my box and it worked fine. This is what I have when I run `winver`:

![image](https://user-images.githubusercontent.com/94054/32986469-f6ec5be8-cc86-11e7-9615-74a5223a7011.png)

It looks like [version 1703 is Creators Update](https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1703_.28Creators_Update.29).

Could you run `winver` and let me know what your version of Windows is? Is it Pro?

**Comment by Spegeli** [comment]
My 2nd PC is running the same Version as you and it works fine but my main PC is running Version 1709 (Build 16299.64) and i got the Problem.
Both are Windows Pro.

To be sure its not my pc, 2-3 other people done the test and they can confirm that its a issue with Version 1709.

**Comment by joelverhagen** [comment]
I tried this on a 1709 machine and reproduced the issue. I've fixed the problem and released a new version of the package (1.6.2):
https://www.nuget.org/packages/Knapcode.TorSharp/1.6.2

Can you give it a try an let me know if it resolves your issue?

**Comment by Spegeli** [comment]
Tyvm seems the problem is solved ;-)
