### ISSUE TITLE
how to set the values in torrc before running?

### ISSUE THREAD

**Issue by drunkwolfs** [joelverhagen/TorSharp#22]
I use a corporate proxy that I would like to specify in the torus settings before it starts. How can i do this?
In addition, can privoxy work normally on the corporate network?

**Comment by joelverhagen** [comment]
Yes, Privoxy should be able to run on a corporate network. You can think of it a bridge from HTTP (what C# can easily talk to) to Tor. It only runs locally and should not be impeded by a corporate firewall. There is a possibility that there are some specific settings in your corporate domain that block Privoxy from running however. 

Concerning connecting to a corporate proxy, this is possible, although not a great experience. I was able to do it by simply editing the `torrc` file to add the following line:

```
HTTPSProxy 1.2.3.4:1234
```

(replacing the IP address and port with your corporate proxy, [Tor docs here](https://www.torproject.org/docs/tor-manual.html.en))

The `torrc` file is by default under the `tor-win32-x.x.x.x\Data\Tor\` directory. This is a subdirectory of the `TorSharpSettings.ExtractedToolsDirectory` pointed at by the property. If it does not exist, you can create an empty file with that one line above in it and TorSharp will leave this existing settings, adding or overwriting settings that it needs to.

Note that if you use `TorSharpToolFetcher` you may get a new version of Tor sometimes so I would recommend only using it once to snap to a set version of tools then removing that part from your code.

It would also be reasonable to add this setting to the `TorSharpSettings` object so you can let TorSharp write this setting out for you.

**Comment by joelverhagen** [comment]
@drunkwolfs, would it be convenient for you if I added `HTTPSProxy` to the C# API so you can define it there instead of having to write to the file yourself?

**Comment by joelverhagen** [comment]
@drunkwolfs, I've added these settings to the official API:
https://www.nuget.org/packages/Knapcode.TorSharp/1.8.0
