### ISSUE TITLE
ConfigureAndStartAsync throws in Knapcode.TorSharp.TorSharpProxy.ExtractTool

### ISSUE THREAD

**Issue by jamesnoys** [joelverhagen/TorSharp#24]
The tools cannot be extracted - seems like something is wrong with the zip archives.

Version: 1.8.2 (NuGet)

Exception:
Object reference not set to an instance of an object.

Class Stack:
   at Knapcode.TorSharp.TorSharpProxy.ExtractTool(Tool tool, Boolean reloadTool)
   at Knapcode.TorSharp.TorSharpProxy.Extract(ToolSettings toolSettings)
   at Knapcode.TorSharp.TorSharpProxy.<InitializeAsync>d__10.MoveNext()

**Comment by Flexx02** [comment]
I Have this same problem.
Downloaded successfully but not extracted

**Comment by joelverhagen** [comment]
Found the problem. About to release 1.8.3.

**Comment by joelverhagen** [comment]
This should fix it for you:
https://www.nuget.org/packages/Knapcode.TorSharp/1.8.3

**Comment by Flexx02** [comment]
Thanks a LOT!!

**Comment by jamesnoys** [comment]
Thank you!
