### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by M4jx** [joelverhagen/TorSharp#27]
I've just built it to test it but I got this issue
![capture](https://user-images.githubusercontent.com/25796885/40846315-8636e838-65b9-11e8-91d8-247319a74be0.PNG)

**Comment by joelverhagen** [comment]
I have improved the messaging around this failure to debug this problem. That being said, I was unable to reproduce the problem. Feel free to re-open if you're still running into the problem.

**Comment by joelverhagen** [comment]
I've improved the error experience in [1.8.4](https://www.nuget.org/packages/Knapcode.TorSharp/1.8.4).
