### ISSUE TITLE
SecurityProtocolType.Ssl3 not supported in last version of ServicePointManager

### ISSUE THREAD

**Issue by spaget** [joelverhagen/TorSharp#28]
Hello, 

The new version of the ServicePointManager do not support the security protocol **SecurityProtocolType.Ssl3**.
https://github.com/dotnet/corefx/blob/a9e01da6f1b3a0dfbc36d17823a2264e2ec47050/src/System.Net.ServicePoint/src/System/Net/ServicePointManager.cs 

It result an error during TorSharpToolFetcher initialization : 
```
System.NotSupportedException
The requested security protocol is not supported.
at System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolType value)
at System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)
at Knapcode.TorSharp.TorSharpToolFetcher.FetchAsync() 
```

See ServicePointManager security protocol validation : 
```
private static void ValidateSecurityProtocol(SecurityProtocolType value)
{
        SecurityProtocolType allowed = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
        if ((value & ~allowed) != 0)
        {
              throw new NotSupportedException(SR.net_securityprotocolnotsupported);
        }
}
```

Thanks.

**Comment by joelverhagen** [comment]
Ah, nice catch. You should be able to work around this by setting `TorSharpSettings.EnableSecurityProtocolsForFetcher` to `false`, but I will put out a fix for this so it doesn't fail if it can't enable a protocol.

**Comment by joelverhagen** [comment]
I've improved the experience in [1.8.4](https://www.nuget.org/packages/Knapcode.TorSharp/1.8.4).
