### ISSUE TITLE
InvalidDataException on ToolFetcher

### ISSUE THREAD

**Issue by pjc0247** [joelverhagen/TorSharp#30]
```
처리되지 않은 예외: System.IO.InvalidDataException: 중앙 디렉터리의 끝 레코드를 찾을 수 없습니다.
   위치: System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   위치: System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   위치: System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   위치: System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   위치: System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   위치: System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName)
   위치: Knapcode.TorSharp.TorSharpProxy.ExtractTool(Tool tool, Boolean reloadTool)
   위치: Knapcode.TorSharp.TorSharpProxy.Extract(ToolSettings toolSettings)
   위치: Knapcode.TorSharp.TorSharpProxy.<InitializeAsync>d__10.MoveNext()
```

Is there any way to setup manually?
Because I already saw [this issue](https://github.com/joelverhagen/TorSharp/issues/23) and it seems that someone have to make a fix everytime link is broken.

**Comment by joelverhagen** [comment]
I tried to repro this issue and could not. My guess is either the Privoxy or the Tor download URL was returning something besides a ZIP file due to a temporary outage.

Either way, I added an FAQ to work around this issue: https://github.com/joelverhagen/TorSharp#how-do-i-set-up-the-tools-manually.

**Comment by contextualweb** [comment]
Can u add instructions on how to download and install  Privoxy and Tor on Linux. I am using Centos 7. The **How do I set up the tools manually?** section refers to Windows only.

**Comment by reft** [comment]
@contextualweb Did you figure it out how to set up for linux?
