### ISSUE TITLE
Problem while  Extracting the Tool  Zip

### ISSUE THREAD

**Issue by bferreirarocha** [joelverhagen/TorSharp#32]
Exception thrown: 'Knapcode.TorSharp.TorSharpException' in mscorlib.dll
An unhandled exception of type 'Knapcode.TorSharp.TorSharpException' occurred in mscorlib.dll
Failed to extract tool 'Tor'. Verify that the .zip at path 'C:\Users\xxxx\AppData\Local\Temp\TorZipped\tor-win32-0.4.0.5.zip' is valid.

**Comment by joelverhagen** [comment]
Is the file at `C:\Users\xxxx\AppData\Local\Temp\TorZipped\tor-win32-0.4.0.5.zip` a .zip? If not, what is it?

To workaround the issue try these steps:
https://github.com/joelverhagen/TorSharp#how-do-i-set-up-the-tools-manually

**Comment by joelverhagen** [comment]
Please feel free to re-open if you are still encountering the issue. Without further information I can't debug what is happening.
