### ISSUE TITLE
Request: Allow to check if new versions are available before update

### ISSUE THREAD

**Issue by AbeniMatteo** [joelverhagen/TorSharp#33]
Currently `TorSharpToolFetcher.FetchAsync` checks for updates and if possible will execute the update.

The update require some time and in my case it will be better to let the user choose to run the outdated version of privoxy\tor (if already installed) or wait for the update.

**Comment by joelverhagen** [comment]
I like this idea. What do you think about a "public bool UseExistingTools { get; set; }" setting on `TorSharpSettings` defaulted to `false` (for backwards compat)?

**Comment by joelverhagen** [comment]
What do you think about this?

https://github.com/joelverhagen/TorSharp/blob/7e6794c8d0d4af47f8682c2e753a6b88d2ca4ed7/TorSharp/TorSharpSettings.cs#L54-L58

If I don't hear from you, I'll just push it out because I think it's pretty solid. Happy to react to your feedback though 😄

**Comment by AbeniMatteo** [comment]
It works but i either choose blindly to use the existing version or try to update. 
I can't check if an existing update exists and choose afterward what to do.

**Comment by joelverhagen** [comment]
So maybe you can pass in a delegate like `Func<string, bool>` so you can return true or false depending on whether the latest version that is already downloaded should be used?

**Comment by AbeniMatteo** [comment]
I think the best solution is to add a method that check only for updates and returns if there is any.
Example:

```cs
var fetcher = new TorSharpToolFetcher(useExistingToolsSettings, client);
var updateAvailable = fetcher.CheckForUpdatesAsync();
if (updateAvailable)
{
    var userWantsToUpdate = AskUser();
    if (userWantsToUpdate)
        fetcher.FetchAsync();
}
```

This addition is completely backward compatible.
What do you think?

**Comment by joelverhagen** [comment]
Nice idea! I'll play around with something like that.

**Comment by joelverhagen** [comment]
This is the shape I went with:

https://github.com/joelverhagen/TorSharp/blob/54ba2413fc97a372021b1bf7eafaa3b9fe076279/TorSharp/TorSharpToolFetcher.cs#L47

`ToolUpdates` has a `HasUpdates` property:

https://github.com/joelverhagen/TorSharp/blob/54ba2413fc97a372021b1bf7eafaa3b9fe076279/TorSharp/ToolUpdates.cs#L19

Works okay for you?

**Comment by AbeniMatteo** [comment]
It works, thanks.

I thought there was a problem and i was trying to understand why all the tools were updated even if only one has updates but it was `ReloadTools = true` flag in the sandbox project. All good.

**Comment by joelverhagen** [comment]
Okay I'll release these changes as 1.9.0.
