### ISSUE TITLE
How we get specific counrty proxy IP?

### ISSUE THREAD

**Issue by Hiren-Evince** [joelverhagen/TorSharp#34]
Please provide configuration so tor can generate proxy ip for specific country.

**Comment by joelverhagen** [comment]
You can set `StrictNodes = true` and `ExitNodes = "{nl}"`. This will use exit nodes in the Netherlands, for example. Use ISO 2 letter country codes. `nl` is just one example. 

These options are on `TorSharpSettings.TorSettings`.

See Tor documentation about these options:
https://2019.www.torproject.org/docs/tor-manual.html.en#ExitNodes
https://2019.www.torproject.org/docs/tor-manual.html.en#StrictNodes

**Comment by Hiren-Evince** [comment]
Thanks @joelverhagen for quick guideline.
