### ISSUE TITLE
Documentation? How to specify exit node country?

### ISSUE THREAD

**Issue by HubKing** [joelverhagen/TorSharp#46]
It seems that there are no documentation... Is the code below how to set the exit node country?

            // configure
            var settings = new TorSharpSettings
            {
		...
            };

            settings.TorExitNodes = "{two letter country code}";

**Comment by joelverhagen** [comment]
The value of `settings.TorExitNodes` (or more preferably `settings.TorSettings.ExitNodes`) is whatever `ExitNodes` in the torrc file accepts:
https://2019.www.torproject.org/docs/tor-manual.html.en#ExitNodes

You can specify multiple country codes like `"US, NL, DE"`
