### ISSUE TITLE
Could not find a part of the path.

### ISSUE THREAD

**Issue by sajjadhosseinpoor** [joelverhagen/TorSharp#47]
hi guy, 
thank you for provided dll,

this is code which i'm using as to demonestrated

            try
            {
                var settings = new TorSharpSettings
                {
                    ZippedToolsDirectory = Path.Combine(Environment.CurrentDirectory, "TorZipped"),
                    ExtractedToolsDirectory = Path.Combine(Environment.CurrentDirectory, "TorExtracted"),
                    PrivoxyPort = 1337,
                    TorSocksPort = 1338,
                    TorControlPort = 1339,
                    TorControlPassword = "foobar"
                };

                // download tools
                // await new TorSharpToolFetcher(settings, new HttpClient()).FetchAsync();

                // execute
                var proxy = new TorSharpProxy(settings);
                var handler = new HttpClientHandler
                {
                    Proxy = new WebProxy(new Uri("http://localhost:" + settings.PrivoxyPort))
                };
                var httpClient = new HttpClient(handler);
                await proxy.ConfigureAndStartAsync();
                Console.WriteLine(await httpClient.GetStringAsync("http://api.ipify.org"));
                await proxy.GetNewIdentityAsync();
                Console.WriteLine(await httpClient.GetStringAsync("http://api.ipify.org"));
                proxy.Stop();
            }
            catch (Exception ex)
            {

            }

but i get Could not find a part of the path, which part of path i dont know?

manually added TorZipped folder, copied files 
TorZipped/tor-win32-0.3.5.8.zip=>Tor/tor.exe
TorZipped/privoxy-win32-3.0.28.zip=>privoxy.exe(and other files beside it)

whats wrong with?
and is this library suitable to run multiple instances of program at same time?

**Comment by joelverhagen** [comment]
Could you provide the full exception text? Also, please include a full recursive directory listing of whatever directory `Environment.CurrentDirectory` is pointing to.

>  and is this library suitable to run multiple instances of program at same time?

You would need different ports and directories for each instance. Right now, TorSharp assumes that it should start and stop the running processes so if you have multiple processes running on same port or directory, you'd run in to problems.

However you can run multiple HTTP requests in parallel within the process -- that's totally fine.

**Comment by joelverhagen** [comment]
I have not hear back so I will close this issue.
