### ISSUE TITLE
Support obfs4 bridge

### ISSUE THREAD

**Issue by Lorymi** [joelverhagen/TorSharp#48]
How we can set obfs4 bridge?

**Comment by joelverhagen** [comment]
I'm not aware of what that even is 😄. From some quick Googling, it looks like an alternative transport for Tor traffic and there is [some documentation](https://github.com/Yawning/obfs4#installation) for how to modify the torrc to talk to `obfs4`. 

So it looks like some custom configuration would need to be applied to Tor. Given how specific this is maybe we need a generic property back added to [`TorSharpTorSettings`](https://github.com/joelverhagen/TorSharp/blob/release/src/TorSharp/TorSharpTorSettings.cs) to allow these properties to be added (something like `Dictionary<string, string>` where the key is the configuration name and the value is everything after the key).

Feel free to make a PR if you are interested in adding this functionality!

**Comment by Lorymi** [comment]
@joelverhagen Hi
See this https://medium.com/@arcdetri/tor-obfs4-bridge-on-windows-41b9bc313a13
Can you implement this

**Comment by joelverhagen** [comment]
I don't have the time to work on additional features right now. I think the fastest way to get this in TorSharp would be for you to contribute a PR with the changes necessary. I'd be happy to review it and add any polish necessary.

**Comment by joelverhagen** [comment]
Resolved with https://github.com/joelverhagen/TorSharp/pull/56, in version 2.3.0. 

See the related settings here:
https://github.com/joelverhagen/TorSharp/blob/ed663a94c347d0fb6e7c85a4f6e2d3abb1c2219d/src/TorSharp/TorSharpTorSettings.cs#L89-L106

**Comment by joelverhagen** [comment]
Thanks again to @AMBULATUR for making this happen!
