### ISSUE TITLE
I get a 403 (Forbidden) error when I make a request with TorSharp.

### ISSUE THREAD

**Issue by themiralay** [joelverhagen/TorSharp#51]
Hello to everyone,
While I normally do not get an error when I make a request, I get a Forbidden (403) error when I create TorSharp and use it as a proxy. The exception example I received is as follows.

![tor](https://user-images.githubusercontent.com/53035239/83316238-692ce780-a22d-11ea-9d9f-3fe248d010db.png)

**Comment by joelverhagen** [comment]
Can you check the torrc under the `%temp%\TorExtracted` to see if it has a hashed password set? This should be set up by TorSharp but maybe it's not happening.

Also, try setting the `ReloadTools` config property to true and see if that helps.

**Comment by themiralay** [comment]
@joelverhagen  I changed the  `%temp%\TorExtracted\tor-win32-0.4.2.7\Data\Tor\torrc `file to password 1234. I added ReloadTools, true parameter in TorSharp Settings. But I'm still getting the same error. I can access the site via Tor Browser. But I get 403 with TorSharp. Can you check the site on TorSharp?

**Comment by joelverhagen** [comment]
Take a look at the response body coming back from `HttpClient`, e.g. `httpClient.GetAsync(...)` then look at `Content.ReadAsStringAsync()`. This site has CloudFlare protection. You can read more about it here:
https://support.cloudflare.com/hc/en-us/articles/200170136-Understanding-Cloudflare-Challenge-Passage-Captcha-

To resolve the challenge you will need to interact with the challenge, e.g. with a full browser.

**Comment by joelverhagen** [comment]
This question is specific to the website you are interacting with and outside of the scope of TorSharp. Please let me know if you have any questions about TorSharp's behavior or functionality.
