### ISSUE TITLE
Custom Log output

### ISSUE THREAD

**Issue by ArcadeArchie** [joelverhagen/TorSharp#52]
Is there already a way to redirect the console output for custom logging?

**Comment by joelverhagen** [comment]
Great idea! Currently there is no way to do it but it could be added without much difficulty. The `VirtualDesktopToolRunner` might be a little harder since Windows API are directly p/invoked but it should be do-able. What sort of interface so you want?

Would something like this work?

```csharp
public interface ITorSharpLogger
{
    void OnOutput(string data);
    void OnError(string data);
}
```

And you pass in an implementation of this `ITorSharpLogger` via `TorSharpSettings.Logger`?

None of this is implemented yet but I want to see what specifically you are thinking could work.

**Comment by ArcadeArchie** [comment]
Doing it with an Inteface isnt such a bad idea but i think doing it over events would be better, like:
```csharp
    interface ITorSharpProxy
    {
        ....
        public event EventHandler<LogEventArgs> OnOutput;
        public event EventHandler<ErrEventArgs> OnError;
        ....
    }


ITorSharpProxy proxy = new TorSharpProxy();
proxy.OnOutput += OnOutput;
proxy.OnError += OnError;

```
or a mix between the two.

**Comment by joelverhagen** [comment]
Sounds good! No clue when I will get to this. It sounds like a solid idea though and it seems quite doable as a community contribution.

**Comment by z3nth10n** [comment]
This is a great project, but I'm also missing this feature, so I decided to implement in on my own!

I [committed some changes](https://github.com/uta-org/TorSharp/commit/272fd4e0979ad755adab6e0cdc2d07b560ea8894) as you can see on my fork. But I'm having troubles, so I decided to ask a question on StackOverflow, any help is appreciated! Thanks!

https://stackoverflow.com/questions/63345753/redirect-stdout-and-stderr-from-process-created-with-winapi

**Comment by developer82** [comment]
Just saw this since I was looking for a way to control the output channel as well... why not implement the use of the standard .NET core ILogger interface?

**Comment by joelverhagen** [comment]
Great point @developer82, this is a very reasonable API to align upon. Want to make a PR to add this capability?

**Comment by developer82** [comment]
@joelverhagen downloaded the code. Will try...

**Comment by joelverhagen** [comment]
I've added support for this. I went with a simple C# event for stdout and another for stderr on `TorSharpProxy`. Try out version 2.11.0. I added this sample to help:
https://github.com/joelverhagen/TorSharp/blob/release/samples/CustomLogging/Program.cs
