### ISSUE TITLE
Error 426

### ISSUE THREAD

**Issue by glararan** [joelverhagen/TorSharp#53]
While making HttpRequest which worked month ago, now I get 
`The remote server returned an error: (426) Upgrade Required.`

If I disable proxy from handler => no TorSharp request works fine.

Any possible issue during TLS 1.1 ending support?

Request require HTTP version 1.1. 2.0 not supported.

**Comment by joelverhagen** [comment]
`426 Upgrade` required is an HTTP status code. If you are seeing this, there is at least _some_ HTTP connection being successfully made. Could you try hitting the same endpoint with [TorBrowser](https://www.torproject.org/download/)?

**Comment by glararan** [comment]
@joelverhagen 
With TorBrowser there is no error. However I have to comment out this line for me to get it working => not using tor
```
            handler = new HttpClientHandler()
            {
                UseCookies = true,
                CookieContainer = Cookies,
                //Proxy = new WebProxy(new Uri("http://localhost:" + settings.PrivoxySettings.Port)),
                AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
            };
```

**Comment by PiotrZimniak** [comment]
I had the same problem with sample `TorSharpSettings`.

```c#
var settings = new TorSharpSettings
{
   ZippedToolsDirectory = Path.Combine(Path.GetTempPath(), "TorZipped"),
   ExtractedToolsDirectory = Path.Combine(Path.GetTempPath(), "TorExtracted"),
   PrivoxySettings = { Port = 1337 },
   TorSettings =
   {
      SocksPort = 1338,
      ControlPort = 1339,
      ControlPassword = "foobar",
   },
};
```
When I change all properties to default values, request return 200 status code.
```c#
var settings = new TorSharpSettings
{
    ZippedToolsDirectory = Path.Combine(Path.GetTempPath(), "TorZipped"),
    ExtractedToolsDirectory = Path.Combine(Path.GetTempPath(), "TorExtracted"),
};
```

**Comment by hartmanfrost** [comment]
Check if tor started and privoxy started, also check open ports on your machine, possibly a port conflict. In my case, vmware opened port 1337 and the proxy did not start

**Comment by joelverhagen** [comment]
I'm going to close this issue. It's quite old. If the issue comes back, please open a new issue with a minimal repro (including the URL you are trying to hit via HTTP).
