### ISSUE TITLE
Bootstrapped 0% (starting) Error

### ISSUE THREAD

**Issue by muratulashozturk** [joelverhagen/TorSharp#54]
Hi, I am using the example code of TorSharp initializing, but when I launch the program, Tor proxy is not starting. I mean It stuck at
```
Oct 31 18:24:17.000 [notice] Bootstrapped 0% (starting): Starting
Oct 31 18:24:18.000 [notice] Starting with guard context "default"
```
And nothing. The bootstrapped should be started but it's not starting. Help me, please. Thanks

**Comment by muratulashozturk** [comment]
Also tried without **TorSharpToolFetcher**. Didn't work.

**Comment by AMBULATUR** [comment]
Probably tor can be blocked in your country, try to use VPN before start.
joelverhagen hardcoded torrc settings, so you can't connect throught obfs4 bridge for avoid possible block in your country.

**Comment by joelverhagen** [comment]
@AMBULATUR, thanks for chiming in! I appreciate the helper. Unfortunately I don't have much time these days to focus on side projects. Work and family puts me pretty close to 100%!

As mentioned here: https://github.com/joelverhagen/TorSharp/issues/48#issuecomment-620710699, I'd be happy to review a contribution to makes such a bridge setting in Tor configuration in the .NET API. For example, this PR provided configuration for the exit node: https://github.com/joelverhagen/TorSharp/pull/11/files.

**Comment by joelverhagen** [comment]
Closing this issue since the exit node configuration is released and I haven't heard back on this issue.
