### ISSUE TITLE
Why not work in WPF?

### ISSUE THREAD

**Issue by vipvodu** [joelverhagen/TorSharp#55]
In wpf I have problem in string:
`var updates = await fetcher.CheckForUpdatesAsync();`

this string can't finish execute and not throw mistake

**Comment by vipvodu** [comment]
with console app I have not problem, but in wpf app - no work

**Comment by vipvodu** [comment]
will be problem with async await. now in wpf all good work. sorry)

**Comment by joelverhagen** [comment]
Good to hear!
