### ISSUE TITLE
Why SendCommandAsync is private?

### ISSUE THREAD

**Issue by davidtavarez** [joelverhagen/TorSharp#68]
I would like to send commands manually but `SendCommandAsync` is private, why? https://github.com/joelverhagen/TorSharp/blob/release/src/TorSharp/Tools/Tor/TorControlClient.cs#L118

**Comment by joelverhagen** [comment]
It's private because no one has needed it until now ☺️.

I'm happy to accept the PR with this change!

**Comment by joelverhagen** [comment]
I've made this method public. Have fun!

Check out version 2.6.0:
https://www.nuget.org/packages/Knapcode.TorSharp/2.6.0
