### ISSUE TITLE
How to open multiple ports in socks?

### ISSUE THREAD

**Issue by SkillartzHD** [joelverhagen/TorSharp#69]
Hello , is there any option to open multiple socks from a single controlport (like 1339)? 

`var settings = new TorSharpSettings
`{

`      SocksPort = 1338,1340,1341...etc
`

`};`

**Comment by joelverhagen** [comment]
TIL this was possible 😄. I've added a new configuration property called `AdditionalSocksPorts`. You can add the `1340, 1341...` there. Tor will listen on those additional ports but the built-in Privoxy integration will only listen to the port specified in `SocksPort` (1338 in your example).

Check out version 2.6.0:
https://www.nuget.org/packages/Knapcode.TorSharp/2.6.0
