### ISSUE TITLE
Tor won't launch with a space in the Username

### ISSUE THREAD

**Issue by Noneatme** [joelverhagen/TorSharp#7]
My Windows Account Name is "Prefix Suffix". I used the example code provded in the readme.md file.
If the downloaded temp folder contains a space, Tor won't launch with the following Exception:

```
Apr 19 11:42:14.890 [warn] Command-line option 'Suffix\AppData\Local\Temp\TorEx
tracted\tor-win32-0.2.7.6\Data\Tor\torrc' with no value. Failing.
Apr 19 11:42:14.890 [err] Reading config failed--see warnings above.

```
The suffix gets interpreted as a new command line option somehow.

**Comment by Noneatme** [comment]
#8

**Comment by joelverhagen** [comment]
Fixed with #8. Thanks! A [new version (1.5.1)](https://www.nuget.org/packages/Knapcode.TorSharp/1.5.1) has been pushed to NuGet.org.

**Comment by joelverhagen** [comment]
> It is possible that line number 30 also needs the special quote marks in order to get Privoxy running. I forgot to mention that.

This needs investigation. I'll look at this at some point.

**Comment by joelverhagen** [comment]
Fixed with https://github.com/joelverhagen/TorSharp/commit/4b81595777baee682261f8053428ae7cf97cefda. Thanks again for your contribution!
