### ISSUE TITLE
Improvement: separate Configure from Start

### ISSUE THREAD

**Issue by kzu** [joelverhagen/TorSharp#70]
Currently, both responsibilities are mixed in the single `ConfigureAndStartAsync` method. 

I found it useful to be able to fully extract+configure the tools separately from actually starting them. For example, to further explore the `torrc` and make additional tweaks before actually starting it.

The proposal is to introduce two new methods: `ConfigureAsync` and `StartAsync` and have `ConfigureAndStartAsync` essentially call one after the other, so the behavior is exactly like it is now:

```csharp
    public static class TorSharpProxyExtensions
    {
        public static async Task ConfigureAndStartAsync(this ITorSharpProxy proxy)
        {
            await proxy.ConfigureAsync().ConfigureAwait(false);
            await proxy.StartAsync().ConfigureAwait(false);
        }
    }

    public interface ITorSharpProxy : IDisposable
    {
        Task ConfigureAsync();
        Task StartAsync();
        Task GetNewIdentityAsync();
        void Stop();
    }
```

This would be source-compatible with the previous versions, although not binary compat (should not be a problem since to update the nuget dependency, you'd need to also ship a new version of your package). The only breaking scenario (for moving `ConfigureAndStartAsync` would be if a *third* project/consumer references a nuget pointing to the older TorSharp, and he explicitly references a newer version of TorSharp in the top-level project. The nuget that depended on the older version of TorSharp would fail at run-time because the method wouldn't be found. 

I consider that to be an extremely rare case, but would still recommend bumping the major version anyway, so that in that case, users can know there's an API breaking change. Note that the addition of new interface members already justifies bumping major, IMO.

(I have this working on my fork).

**Comment by joelverhagen** [comment]
This shipped in version 2.7.0:
https://www.nuget.org/packages/Knapcode.TorSharp/2.7.0

Thanks @kzu!
