### ISSUE TITLE
Improvement: add a link to a full tor configuration sample

### ISSUE THREAD

**Issue by kzu** [joelverhagen/TorSharp#71]
When applying the configuration to the `torrc` file, it would be useful to point to a more comprehensive example of all the available options, even if they aren't directly surfaced by TorSharp.

The [sample at the torproject](https://github.com/torproject/tor/blob/master/src/config/torrc.sample.in) would be a good candidate, I think.

**Comment by joelverhagen** [comment]
This shipped in version 2.7.0:
https://www.nuget.org/packages/Knapcode.TorSharp/2.7.0

Thanks @kzu!
