### ISSUE TITLE
Use tor-win64 when running on X64 Windows

### ISSUE THREAD

**Issue by kzu** [joelverhagen/TorSharp#74]
The releases contain tor-win64, which should be used when running on Windows X64. instead of hardcoding win-32.

See https://dist.torproject.org/torbrowser/10.5a15/

Perhaps there's a reason why this is fixed to win32?

PS: if there's no particular reason not to use win64, I can send a PR, of course :)

**Comment by joelverhagen** [comment]
Release in TorSharp 2.8.0. Thanks again, @kzu!
https://www.nuget.org/packages/Knapcode.TorSharp/2.8.0
