### ISSUE TITLE
Stuck endlessly when one of Privoxy mirrors is down

### ISSUE THREAD

**Issue by JanPokorny** [joelverhagen/TorSharp#80]
Currently, https://www.silvester.org.uk/privoxy/ is down -- it returns HTTP code 509:

![image](https://user-images.githubusercontent.com/4580066/122274899-5db56880-cee3-11eb-8529-0a17bab58d8e.png)

Even though the other two mirrors are fine, this makes `TorSharpToolFetcher.FetchAsync` stuck endlessly, not even throwing an exception, just plain not ever resolving the `await`. The following line seems to be the culprit:

https://github.com/joelverhagen/TorSharp/blob/7381dae0299d30f6430296efbd9e03ba368358b0/src/TorSharp/Tools/FetcherHelpers.cs#L33

**Comment by JanPokorny** [comment]
Also, funnily, `UseExistingTools = true` and placing the zips in the zipped tools folder does not prevent this unless the tools are already extracted. When the extracted tools folder is empty, it still gets stuck. This prevents me from working the issue around by packaging the ZIPs with my application directly, since the tool fetcher gets stuck either way.

**Comment by joelverhagen** [comment]
Well that's certainly not by design! Thanks for taking the time to report this. Would it be possible to get a fiddler trace of the exact response returned there? It might help reproducing the issue if and when the mirror comes back up.

**Comment by JanPokorny** [comment]
@joelverhagen Here's the Fiddler export, however it's nothing more than a simple 509 reply.
[2021-06-16.zip](https://github.com/joelverhagen/TorSharp/files/6665605/2021-06-16.zip)

**Comment by joelverhagen** [comment]
This is strange. I see the 509 on my end (web browser and in TorSharp) but I don't see a hang. If you run the sample app in this repo, does the problem repro? If you comment out this line does it fix the problem?
https://github.com/joelverhagen/TorSharp/blob/7381dae0299d30f6430296efbd9e03ba368358b0/src/TorSharp/Tools/Privoxy/PrivoxyFetcher.cs#L65

What platform are you running? .NET Framework or .NET Core? Windows or Linux?

Since I can't reproduce the hang on my end (509 _does_ appear...) I'm not sure what's going yet.

**Comment by JanPokorny** [comment]
@joelverhagen The test app indeed works normally. I ended up slashing down my app to create the minimal example, and this is the result. It's a .NET Framework 4.6.1 WinForms app running on Windows 10, and the hang happens _only_ when the tool fetcher is invoked inside `Form.OnLoad`. This makes me think that it might be just me using `async` incorrectly and causing a deadlock (I just use `task.Wait()`), but the funny thing is that until now, it worked fine.

[TorSharpTest.zip](https://github.com/joelverhagen/TorSharp/files/6668439/TorSharpTest.zip)

**Comment by joelverhagen** [comment]
@JanPokorny, I figured it out. I had some `Task.Yield()` calls in my code (not sure why). I think this has a custom awaiter than makes your WinForms app deadlock. I will release a new version with this bug fix.

**Comment by joelverhagen** [comment]
I've release version 2.8.1 with this fix.
https://www.nuget.org/packages/Knapcode.TorSharp/2.8.1

**Comment by JanPokorny** [comment]
@joelverhagen Thank you very much! Async in C# is dark magic to me 😁
