### ISSUE TITLE
Unhandled exception. Knapcode.TorSharp.TorSharpException: No version of Tor was found under /tmp/TorZipped.

### ISSUE THREAD

**Issue by Adri-Donn** [joelverhagen/TorSharp#82]
Hi, 

Thank you for sharing this great project !

I use it on windows (works like a charm) and in debian 10.

I used the example code :

```
ZippedToolsDirectory = Path.Combine(Path.GetTempPath(), "TorZipped"),
                ExtractedToolsDirectory = Path.Combine(Path.GetTempPath(), "TorExtracted"),
                PrivoxySettings = { Port = privoxySettingsPort },
                EnableSecurityProtocolsForFetcher = false,
                TorSettings =
                {
                    SocksPort = socksPort,
                    ControlPort = controlPort,
                    ControlPassword = "foobar",
                }
```

And :

```
var fetcher = new TorSharpToolFetcher(torSharpSettings, new HttpClient());
            var updates = await fetcher.CheckForUpdatesAsync();
            Console.WriteLine($"Current Privoxy: {updates.Privoxy.LocalVersion?.ToString() ?? "(none)"}");
            Console.WriteLine($" Latest Privoxy: {updates.Privoxy.LatestDownload.Version}");
            Console.WriteLine();
            Console.WriteLine($"Current Tor: {updates.Tor.LocalVersion?.ToString() ?? "(none)"}");
            Console.WriteLine($" Latest Tor: {updates.Tor.LatestDownload.Version}");
            Console.WriteLine();
            if (updates.HasUpdate)
            {
                await fetcher.FetchAsync(updates);
            }
```

But with debian i get a 

Unhandled exception. Knapcode.TorSharp.TorSharpException: No version of Tor was found under /tmp/TorZipped.

The folders TorZipped is really empty :/ 

Did you know what i'm doing wrong ?

Many thanks for your help and have a great day :)

**Comment by hosseinRezaei188** [comment]
download "Windows Expert Bundle" from 
[torproject](https://www.torproject.org/download/tor/)
and place in "C:\Users\{UserName}\AppData\Local\Temp\TorZipped"
note: replace 64 when your os is 64 bit in tor-*.zip file, like "tor-win64-0.4.5.10.zip"

for privoxy download from this link:
[privoxy](https://www.privoxy.org/sf-download-mirror/Win32/3.0.26%20%28stable%29/)
and also place in "C:\Users\{UserName}\AppData\Local\Temp\TorZipped"

**Comment by joelverhagen** [comment]
The binary artifacts provided by the Tor project changed recently. If this problem is still happening, fell free to open a new issue.
