### ISSUE TITLE
Run multiple instance at the same time

### ISSUE THREAD

**Issue by karmamaster** [joelverhagen/TorSharp#88]
Hello,
I am trying to open multiple instance of TorSharp at the same time (Using unique ports setting for each, including sock port, control port, and control port). But when I try to run: `proxy.ConfigureAndStartAsync();` then the previous opened port can not be access. So there is any ways that can help to run multiple instance with TorSharp?

**Comment by joelverhagen** [comment]
I've added an FAQ about this in the README and fixed a couple of bugs. Give it a try in version 2.10.0!
