### ISSUE TITLE
TorFetcher TorSharpException: No version of Tor could be found under base URL 

### ISSUE THREAD

**Issue by sanctusmob** [joelverhagen/TorSharp#91]
TorSharpException: No version of Tor could be found under base URL https://dist.torproject.org/torbrowser/ with pattern tor-win64-(?<Version>[\d\.]+)\.zip$.

The url must change.

![image](https://user-images.githubusercontent.com/13434486/208627319-623a27d4-1144-4874-aff3-055f09e5c4c3.png)

**Comment by sanctusmob** [comment]
Also patterns must be changed the in GetFileNamePatternAndFormat

**Comment by joelverhagen** [comment]
@sanctusmob, thank you for bringing this to my attention.

Special thanks to @ZimM-LostPolygon for opening a PR to fix the problem! 🏆

I've released version 2.9.0 which is fixed.
https://www.nuget.org/packages/Knapcode.TorSharp/2.9.0
